
import FormField = require('dw/web/FormField')
import FormGroup = require('dw/web/FormGroup');
import FormAction = require('dw/web/FormAction');
// autogeneratedfile

/** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#2)*/
declare class FormFriendlist extends FormGroup {
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#5) */
	name : FormField<string>
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#9) */
	phone : FormField<string>
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#17) */
	date : FormField<string>
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#20) */
	nickname : FormField<string>
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#25) */
	apply : FormAction
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#26) */
	remove : FormAction
}

declare global {
interface SFCCForms {
	friendlist: FormFriendlist
}
}


/****** SRFA *******/

interface SfraAction {
    description: string | null;
    label: string | null;
    submitted: boolean | null;
    triggered: boolean | null;
    formType: string;
}

interface SfraFiledOptions {
	checked: boolean,
	htmlValue: string,
	label: string,
	id: string,
	selected: boolean,
	value: string
}

interface SfraFieldBoolean {
	checked: boolean;
	selected: boolean;
}

interface SfraFieldString {
	maxLength: number;
	minLength: number;
	regEx: string
}

interface SfraFieldInteger {
	maxValue: number;
	minValue: number;
}

interface SfraField<T> {
	valid: boolean;
	error: string | null
	readonly attributes: string;
	value: T;
	options: SfraFiledOptions[];
	selectedOption: string;
	formType: string;

	htmlValue: string,
	mandatory: boolean,
	dynamicHtmlName: string
	htmlName: string
}

interface SfraFormBase<T> {
	clear() : void;
	copyFrom(src: object): void;
	toObject(): any;
	valid: boolean;
	base: T
	htmlName: string,
	dynamicHtmlName: string,
	error: string | null,
	attributes: string,
	formType: 'formGroup'
}
/** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#2)*/
interface SfraFormFriendlist extends SfraFormBase<FormFriendlist> {
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#5) */
	name : SfraField<string> & SfraFieldString
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#9) */
	phone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#17) */
	date : SfraField<string> & SfraFieldString
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#20) */
	nickname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#25) */
	apply : SfraAction
	 /** @source [definition](file:e:\umeshbackup\friendlist\umeshCustomCartridge\cartridges\umeshcustom\cartridge\forms\default\friendlist.xml#26) */
	remove : SfraAction
}

declare global {
interface SFRAServerForms {
	getForm(name: 'friendlist'): SfraFormFriendlist
}
}

declare global {
interface SRFAForms {
	friendlist: SfraFormFriendlist
}
}